name: CICD
on: [push, pull_request]
jobs:
  #Build Workflow
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14.0"
      
      - name: Install Dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      
      - name: Build
        run: go build -o compiled/libmatch.so -buildmode=c-shared

      - name: Run vet & lint
        run: |
          go vet .
          golint .
